services:
  postgres:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: huokan
      POSTGRES_USER: huokan
      POSTGRES_PASSWORD: huokan
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
volumes:
  db_data: {}
