name: Test and Release

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: huokan_test
          POSTGRES_USER: huokan
          POSTGRES_PASSWORD: huokan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build HuokanServer
      # - name: Unit Tests
      #   run: ./UnitTest.sh
      - name: Integration Tests
        run: bash IntegrationTest.sh
      - name: End to End Tests
        run: bash EndToEndTest.sh

      - name: Install Swashbuckle CLI
        run: dotnet tool install -g --version 6.2.3 Swashbuckle.AspNetCore.Cli

      - name: Generate openapi.json
        # cd to EndToEndTests to use the e2e appsettings.json
        run: (cd HuokanServer.EndToEndTests && swagger tofile --output ../openapi.json ../HuokanServer/bin/Debug/net6.0/HuokanServer.dll v1)

      - name: Upload openapi.json artifact
        uses: actions/upload-artifact@v2
        with:
          name: openapi.json
          path: openapi.json

  generate_typescript_sdk:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Download openapi.json
        uses: actions/download-artifact@v2
        with:
          name: openapi.json

      - name: Generate SDK
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.json \
            -g typescript-fetch \
            -c /local/OpenAPI/typescript.yml \
            -o /local/huokanclient-ts
          sudo chown -R $USER:$USER huokanclient-ts
      - name: Run typescript sdk modifications
        run: bash OpenAPI/typescript-modifications.sh

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: ${{ secrets.NPM_REGISTRY }}
          token: ${{ secrets.NPM_TOKEN }}
          package: ./huokanclient-ts/package.json
          access: restricted

  generate_python_sdk:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          path: HuokanServer
      - uses: actions/checkout@v2
        with:
          repository: huokan/huokanapiclient-python
          ssh-key: ${{ secrets.HUOKANAPICLIENT_PYTHON_DEPLOY_KEY }}
          path: huokanapiclient-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Download openapi.json
        uses: actions/download-artifact@v2
        with:
          name: openapi.json

      - name: Install openapi-python-client
        run: pip install openapi-python-client
      - name: Generate SDK
        run: openapi-python-client generate --path openapi.json --config HuokanServer/OpenAPI/python.yml
      - name: Remove all old files
        run: |
          cd huokanapiclient-python
          git ls-files -z | xargs -0 rm -f
          cd ..
      - name: Move into huokanapiclient-python repository
        run: |
          mv huokanapiclient/* huokanapiclient-python
          mv huokanapiclient/.[!.]* huokanapiclient-python

      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.HUOKANAPICLIENT_PYTHON_DEPLOY_KEY }}
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: huokanapiclient-python
          commit_message: Regenerate SDK
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
