name: Test and Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      # - name: Unit Tests
      #   run: ./UnitTest.sh
      - name: Integration Tests
        run: ./IntegrationTest.sh
      - name: End to End Tests
        run: ./EndToEndTest.sh
