name: Test and Release

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: huokan_test
          POSTGRES_USER: huokan
          POSTGRES_PASSWORD: huokan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      # - name: Unit Tests
      #   run: ./UnitTest.sh
      - name: Integration Tests
        run: bash IntegrationTest.sh
      - name: End to End Tests
        run: bash EndToEndTest.sh
