name: Generate TypeScript SDK

on: [push]

jobs:
  generate_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

  generate_openapi:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    services:
      postgres:
        image: postgres:alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: huokan_test
          POSTGRES_USER: huokan
          POSTGRES_PASSWORD: huokan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install Swashbuckle CLI
        run: dotnet tool install -g --version 6.2.2 Swashbuckle.AspNetCore.Cli

      - name: Build
        run: dotnet build HuokanServer
      - name: Generate openapi.json
        # cd to EndToEndTests to use the e2e appsettings.json
        run: (cd HuokanServer.EndToEndTests && swagger tofile --output ../openapi.json ../HuokanServer/bin/Debug/net5.0/HuokanServer.dll v1)

      - name: Generate SDK
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.json \
            -g typescript-fetch \
            -c /local/OpenAPI/typescript.yml \
            -o /local/huokanclient-ts
          sudo chown -R $USER:$USER huokanclient-ts

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: ${{ secrets.NPM_REGISTRY }}
          token: ${{ secrets.NPM_TOKEN }}
          package: ./huokanclient-ts/package.json
          access: restricted
